### ISSUE TITLE
youtube homapage shows：something went wrong

### ISSUE THREAD

**Issue by 3rdQuasar** [arichornlover/YouTubeRebornPlus#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:16.2
- Device model:xsmax
- Sideload tool (AltStore, SideStore, Sideloadly, TrollStore,...):trollstore
- The specific version of YouTubeRebornPlus (**latest** or **newest** is **NOT** a version number!):v19.05.3 4.2.4
![675997C0-60E4-4371-AAC0-8232613AA219](https://github.com/arichornlover/YouTubeRebornPlus/assets/49695505/7fbf902f-839b-4879-99ff-b2873e28bba3)

### Describe the bug

the app was working fine till yesterday suddenly give this error,so decided to install pre release version and it work but can’t watch live, so give the latest release se v19.05.3 4.2.4 a new try but the error is still there 

### Steps to reproduce the issue

1. Open app
2. Error
3. 

### Are you using the newest version of YouTubeRebornPlus? If not, why?

✅ Yes, I'm using the latest version of YouTubeRebornPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by TheNightRider12** [comment]
I am getting a similar issue. I am getting an error message saying “Error Loading. Tap to retry.” Nothing will work.

**Comment by iamnhx** [comment]
Older versions work fine.

**Comment by TheNightRider12** [comment]
Updating to the latest release, [Latest Release](https://github.com/arichornlover/YouTubeRebornPlus/releases/tag/v19.06.2-4.2.5)
Seems to fix the issue on my end.
