### ISSUE TITLE
[Bug] Cercube login not possible

### ISSUE THREAD

**Issue by obito26m** [arichornlover/YouTubeRebornPlus#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.4.1.a
- Device model:13 pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore 
- The specific version of CercubePlus (**latest** or **newest** is **NOT** a version number!): v18.18.2-5.3.11

### Describe the bug

![IMG_0376](https://github.com/arichorn/CercubePlusExtra/assets/41232458/7326f6d7-a261-4fa4-bb52-9b87415bf198)

As you can see in the picture I cannot log in

### Steps to reproduce the issue

1. On cercube setting
2. Then go to Login
3. And the error comes

### Are you using the newest version of CercubePlus? If not, why?

✅ Yes, I'm using the latest version of CercubePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Would be nice if this is fixed since I bought cercube acc

**Comment by Ketarmin** [comment]
Maybe the Cercube dev shut down the sever for the login 

I’m luckily still logged in

**Comment by Ketarmin** [comment]
@obito26m the login was only there to check if you bought Cercube to remove ads, I think
